# Generated by Django 6.0.6 on 2026-06-06 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('member', '💳 Membre (Scanner QR + points)'), ('admin', '👑 Administrateur (Accès complet)'), ('owner', '👨\u200d💼 Propriétaire (Gestionnaire)')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente (invitation envoyée)'), ('active', 'Actif'), ('inactive', 'Inactif')], default='pending', max_length=20)),
                ('invitation_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.merchantprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'ordering': ['-created_at'],
                'unique_together': {('merchant', 'email')},
            },
        ),
    ]
