# Generated by Django 6.0.6 on 2026-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merchantprofile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_api_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token API WhatsApp'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_api_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL API WhatsApp'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='Notifications WhatsApp actives'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_instance_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Instance WhatsApp'),
        ),
    ]
