# Generated by Django 6.0.6 on 2026-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merchantprofile_whatsapp_api_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='whatsapp_api_token',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='whatsapp_api_url',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_connected',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Connecté'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_instance_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Instance WhatsApp'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité WhatsApp'),
        ),
    ]
