# Generated by Django 6.0.6 on 2026-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_whatsapp_per_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clé API WhatsApp'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_api_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Gateway WhatsApp'),
        ),
    ]
