# Generated by Django 6.0.6 on 2026-07-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_onboarding'),
        ('accounts', '0006_merchantprofile_whatsapp_api_key_and_more'),
    ]

    operations = [
    ]
