# Generated by Django 6.0.6 on 2026-07-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merchantprofile_slug'),
        ('accounts', '0007_merge_20260704_1521'),
    ]

    operations = [
    ]
