# Generated by Django 6.0.6 on 2026-07-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20260704_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
