# Generated by Django 6.0.6 on 2026-07-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_onboardingstep_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='require_membership_approval',
            field=models.BooleanField(default=True, help_text="Les clients doivent être approuvés avant d'utiliser leur carte.", verbose_name='Validation manuelle des adhésions'),
        ),
    ]
