# Generated by Django 4.2.30 on 2026-06-02 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('stamp_count', models.PositiveIntegerField(default=0, verbose_name='Tampons')),
                ('total_stamps_ever', models.PositiveIntegerField(default=0)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('google_wallet_object_id', models.CharField(blank=True, max_length=255)),
                ('google_wallet_linked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carte de fidélité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StampHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('stamped_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='loyalty.loyaltycard')),
                ('stamped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tamponné par')),
            ],
            options={
                'verbose_name': 'Historique tampon',
                'ordering': ['-stamped_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='loyalty.loyaltycard')),
            ],
            options={
                'verbose_name': 'Récompense',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du programme')),
                ('color_primary', models.CharField(default='#0E0F0D', max_length=7, verbose_name='Couleur principale')),
                ('color_secondary', models.CharField(default='#D4FF4E', max_length=7, verbose_name='Couleur secondaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='programs/logos/')),
                ('stamps_needed', models.PositiveIntegerField(default=10, verbose_name='Tampons pour une récompense')),
                ('reward_description', models.CharField(default='1 article offert', max_length=255, verbose_name='Description de la récompense')),
                ('active', models.BooleanField(default=True)),
                ('google_wallet_class_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='accounts.merchantprofile')),
            ],
            options={
                'verbose_name': 'Programme de fidélité',
            },
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='loyalty.loyaltyprogram'),
        ),
    ]
