# Generated by Django 4.2.30 on 2026-06-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stamphistory',
            options={'ordering': ['-stamped_at'], 'verbose_name': 'Historique Transaction'},
        ),
        migrations.RemoveField(
            model_name='loyaltycard',
            name='stamp_count',
        ),
        migrations.RemoveField(
            model_name='loyaltycard',
            name='total_stamps_ever',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='stamps_needed',
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde actuel'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='total_accumulated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cumul total'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_per_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Pour 'visites', mettre 1. Pour 'montant', points pour chaque 1000 XAF par exemple.", max_digits=10, verbose_name='Points par unité (visite ou 1000 XAF)'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='program_type',
            field=models.CharField(choices=[('visits', 'Nombre de visites (Tampons)'), ('points', 'Points cumulés'), ('spend', 'Montant dépensé')], default='visits', max_length=20, verbose_name='Type de programme'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='reward_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Nombre de tampons ou points nécessaires.', verbose_name='Seuil pour une récompense'),
        ),
        migrations.AddField(
            model_name='stamphistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='stamped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
    ]
