# Generated by Django 6.0.5 on 2026-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_stamphistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='card_template',
            field=models.CharField(choices=[('classic', 'Classique (Épuré)'), ('glass', 'Vitre (Glassmorphism)'), ('bold', 'Bold (Urbain & Impactant)'), ('luxury', 'Luxe (Sérif & Élégance)')], default='classic', max_length=20, verbose_name='Modèle de carte'),
        ),
    ]
