# Generated by Django 6.0.6 on 2026-06-08 12:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teammember'),
        ('loyalty', '0003_loyaltyprogram_card_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(choices=[('XOF', 'Franc CFA Ouest africain 🇸🇳'), ('EUR', 'Euro 🇪🇺'), ('USD', 'Dollar américain 🇺🇸')], max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la devise')),
                ('symbol', models.CharField(max_length=5, verbose_name='Symbole')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='loyaltycard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Carte de fidélité', 'verbose_name_plural': 'Cartes de fidélité'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'ordering': ['-created_at'], 'verbose_name': 'Programme de fidélité', 'verbose_name_plural': 'Programmes de fidélité'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-unlocked_at'], 'verbose_name': 'Récompense', 'verbose_name_plural': 'Récompenses'},
        ),
        migrations.AlterModelOptions(
            name='stamphistory',
            options={'ordering': ['-stamped_at'], 'verbose_name': 'Historique Transaction', 'verbose_name_plural': 'Historiques Transaction'},
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Carte active'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimée'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='currency',
            field=models.CharField(choices=[('XOF', 'Franc CFA Ouest africain 🇸🇳'), ('EUR', 'Euro 🇪🇺'), ('USD', 'Dollar américain 🇺🇸')], default='XOF', help_text='La devise utilisée pour le programme', max_length=3, verbose_name='Devise de base'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du programme'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='reward_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valeur estimée de la récompense en devise de base', max_digits=10, verbose_name='Valeur de la récompense (en devise de base)'),
        ),
        migrations.AddField(
            model_name='reward',
            name='code',
            field=models.CharField(default=2, editable=False, max_length=20, unique=True, verbose_name='Code de récompense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_redeemed', to=settings.AUTH_USER_MODEL, verbose_name='Utilisée par'),
        ),
        migrations.AddField(
            model_name='stamphistory',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Ajout'), ('subtract', 'Déduction'), ('redeem', 'Utilisation récompense'), ('refund', 'Remboursement')], default='add', max_length=20, verbose_name='Type de transaction'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Solde actuel'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='google_wallet_linked',
            field=models.BooleanField(default=False, verbose_name='Liée à Google Wallet'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='google_wallet_object_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Wallet Object ID'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='loyalty.loyaltyprogram', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token QR'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='total_accumulated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cumul total'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='google_wallet_class_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Wallet Class ID'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='programs/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='accounts.merchantprofile', verbose_name='Commerçant'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='points_per_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Pour 'visites': 1. Pour 'montant': points pour chaque 1000 XOF par exemple.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Points par unité'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='reward_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Nombre de tampons ou points nécessaires.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Seuil pour une récompense'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='loyalty.loyaltycard', verbose_name='Carte'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='redeemed',
            field=models.BooleanField(default=False, verbose_name='Utilisée'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Utilisée le'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Déverrouillée le'),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='loyalty.loyaltycard', verbose_name='Carte'),
        ),
        migrations.AddIndex(
            model_name='loyaltycard',
            index=models.Index(fields=['qr_token'], name='loyalty_loy_qr_toke_5d1498_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycard',
            index=models.Index(fields=['program', 'is_deleted'], name='loyalty_loy_program_dd4730_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['card', 'redeemed'], name='loyalty_rew_card_id_88f5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='stamphistory',
            index=models.Index(fields=['card', '-stamped_at'], name='loyalty_sta_card_id_d83076_idx'),
        ),
    ]
