# Generated by Django 6.0.6 on 2026-06-08 13:32

import django.core.validators
import django.db.models.deletion
import apps.loyalty.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teammember'),
        ('loyalty', '0004_currency_alter_loyaltycard_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltycard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-unlocked_at']},
        ),
        migrations.AlterModelOptions(
            name='stamphistory',
            options={'ordering': ['-stamped_at']},
        ),
        migrations.RemoveIndex(
            model_name='loyaltycard',
            name='loyalty_loy_qr_toke_5d1498_idx',
        ),
        migrations.RemoveIndex(
            model_name='loyaltycard',
            name='loyalty_loy_program_dd4730_idx',
        ),
        migrations.RemoveIndex(
            model_name='reward',
            name='loyalty_rew_card_id_88f5f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='stamphistory',
            name='loyalty_sta_card_id_d83076_idx',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='google_wallet_class_id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('XOF', 'Franc CFA Ouest africain 🇸🇳'), ('EUR', 'Euro 🇪🇺'), ('USD', 'Dollar américain 🇺🇸')], max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='customer_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='google_wallet_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='google_wallet_object_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='loyalty.loyaltyprogram'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='total_accumulated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='card_template',
            field=models.CharField(choices=[('classic', 'Classic'), ('glass', 'Glass'), ('bold', 'Bold'), ('luxury', 'Luxury')], default='classic', max_length=20),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='color_primary',
            field=models.CharField(default='#0E0F0D', max_length=7),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='color_secondary',
            field=models.CharField(default='#D4FF4E', max_length=7),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='programs/logos/'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='accounts.merchantprofile'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='points_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='program_type',
            field=models.CharField(choices=[('visits', 'Visites'), ('points', 'Points'), ('spend', 'Dépenses')], default='visits', max_length=20),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='reward_description',
            field=models.CharField(default='1 article offert', max_length=255),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='reward_threshold',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='reward_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reward',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='loyalty.loyaltycard'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='code',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reward',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='loyalty.loyaltycard'),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='stamped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Ajout'), ('subtract', 'Déduction'), ('redeem', 'Récompense'), ('refund', 'Remboursement')], default='add', max_length=20),
        ),
    ]
