# Generated by Django 6.0.6 on 2026-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_alter_loyaltycard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loyaltycard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stamphistory',
            options={},
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='wallet_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='google_wallet_class_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
