# Generated by Django 6.0.6 on 2026-06-14 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0009_reward_code_model_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name': 'Devise', 'verbose_name_plural': 'Devises'},
        ),
        migrations.AlterModelOptions(
            name='loyaltycard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Carte de fidélité'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'verbose_name': 'Programme de fidélité'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-unlocked_at'], 'verbose_name': 'Récompense'},
        ),
        migrations.AlterModelOptions(
            name='stamphistory',
            options={'ordering': ['-stamped_at'], 'verbose_name': 'Historique Transaction'},
        ),
        migrations.RemoveField(
            model_name='reward',
            name='redeemed_by',
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la devise'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5, verbose_name='Symbole'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde actuel'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='customer_name',
            field=models.CharField(max_length=150, verbose_name='Nom du client'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='total_accumulated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cumul total'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='card_template',
            field=models.CharField(choices=[('classic', 'Classique (Épuré)'), ('glass', 'Vitre (Glassmorphism)'), ('bold', 'Bold (Urbain & Impactant)'), ('luxury', 'Luxe (Sérif & Élégance)')], default='classic', max_length=20, verbose_name='Modèle de carte'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='color_primary',
            field=models.CharField(default='#0E0F0D', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='color_secondary',
            field=models.CharField(default='#D4FF4E', max_length=7, verbose_name='Couleur secondaire'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='currency',
            field=models.CharField(choices=[('XOF', 'Franc CFA Ouest africain 🇸🇳'), ('EUR', 'Euro 🇪🇺'), ('USD', 'Dollar américain 🇺🇸')], default='XOF', help_text='La devise utilisée pour le programme', max_length=3, verbose_name='Devise de base'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du programme'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom du programme'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='points_per_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Pour 'visites', mettre 1. Pour 'montant', points pour chaque 1000 XAF par exemple.", max_digits=10, verbose_name='Points par unité (visite ou 1000 XAF)'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='program_type',
            field=models.CharField(choices=[('visits', 'Nombre de visites (Tampons)'), ('points', 'Points cumulés'), ('spend', 'Montant dépensé')], default='visits', max_length=20, verbose_name='Type de programme'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='reward_description',
            field=models.CharField(default='1 article offert', max_length=255, verbose_name='Description de la récompense'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='reward_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Nombre de tampons ou points nécessaires.', verbose_name='Seuil pour une récompense'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='reward_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valeur estimée de la récompense en devise de base', max_digits=10, verbose_name='Valeur de la récompense (en devise de base)'),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='stamped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='stamphistory',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Ajout'), ('subtract', 'Déduction'), ('redeem', 'Récompense'), ('refund', 'Remboursement')], default='add', max_length=20, verbose_name='Type de transaction'),
        ),
    ]
