# Generated by Django 6.0.6 on 2026-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_alter_currency_options_alter_loyaltycard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='custom_html',
            field=models.TextField(blank=True, help_text='Utilisez {name}, {phone}, {balance}, {total}, {logo} comme variables.', verbose_name='Code HTML personnalisé'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='use_custom_design',
            field=models.BooleanField(default=False, verbose_name='Utiliser un design HTML personnalisé'),
        ),
    ]
