# Generated by Django 6.0.6 on 2026-07-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0015_program_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='font_family',
            field=models.CharField(choices=[('sans-serif', 'Sans-serif'), ('serif', 'Serif'), ('monospace', 'Monospace'), ('cursive', 'Cursive')], default='sans-serif', max_length=20, verbose_name='Police du titre'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='font_size',
            field=models.CharField(choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand')], default='medium', max_length=10, verbose_name='Taille du texte'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='font_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italique'), ('bold', 'Gras')], default='normal', max_length=10, verbose_name='Style du texte'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='gradient_direction',
            field=models.CharField(choices=[('135deg', 'Diagonal (↘)'), ('90deg', 'Horizontal (→)'), ('180deg', 'Vertical (↓)'), ('45deg', 'Diagonal inverse (↗)'), ('radial', 'Radial (○)')], default='135deg', max_length=20, verbose_name='Direction du dégradé'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='gradient_intensity',
            field=models.PositiveIntegerField(default=50, help_text="Intensité de l'effet de dégradé (0-100)", verbose_name='Intensité du dégradé'),
        ),
    ]
