# Generated by Django 6.0.6 on 2026-07-20 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0016_loyaltyprogram_font_family_loyaltyprogram_font_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='membership_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('revoked', 'Révoqué')], default='approved', max_length=20, verbose_name="Statut d'adhésion"),
        ),
    ]
