# Generated by Django 4.2.30 on 2026-06-02 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150, verbose_name='Nom du commerce')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('country', models.CharField(default='Sénégal', max_length=100, verbose_name='Pays')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchants/logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Marchand',
            },
        ),
    ]
